# Generated by Django 4.2.7 on 2024-06-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitions',
            old_name='to_account',
            new_name='to_account_number',
        ),
    ]
