# Generated by Django 4.2.7 on 2024-06-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0003_rename_transitions_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='t_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'transfer')], default='Null', max_length=8),
        ),
        migrations.AlterField(
            model_name='transition',
            name='to_account_number',
            field=models.IntegerField(blank=True),
        ),
    ]
