# Generated by Django 4.2.7 on 2024-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0004_transition_t_type_alter_transition_to_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='t_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer')], default='Null', max_length=8),
        ),
    ]
