# Generated by Django 4.2.7 on 2024-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0006_rename_transition_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=212121),
            preserve_default=False,
        ),
    ]
