# Generated by Django 4.2.7 on 2024-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0007_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=123123, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
