# Generated by Django 4.2.7 on 2024-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0008_transaction_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('sent', 'Sent'), ('received', 'Received')], default='Null', max_length=8),
        ),
    ]
