# Generated by Django 4.2.7 on 2024-06-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0009_alter_transaction_current_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='current_balance',
        ),
    ]
