# Generated by Django 4.2.7 on 2024-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0010_remove_transaction_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.IntegerField(null=True),
        ),
    ]
