# Generated by Django 4.2.7 on 2024-06-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0011_alter_transaction_to_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.IntegerField(blank=True),
        ),
    ]
