# Generated by Django 4.2.7 on 2024-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0012_alter_transaction_to_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
