# Generated by Django 4.2.7 on 2024-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0013_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
