# Generated by Django 4.2.7 on 2024-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_api', '0014_alter_transaction_to_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
